[0m16:31:35.015542 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8E46FF7C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8E6F19970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8E6F19730>]}


============================== 16:31:35.028693 | 1b0f4e9d-b68d-4feb-9e48-3fed68dc0378 ==============================
[0m16:31:35.028693 [info ] [MainThread]: Running with dbt=1.7.13
[0m16:31:35.029724 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '.', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt init --profiles-dir .', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:31:51.728600 [debug] [MainThread]: Starter project path: C:\Users\caioc\Anaconda3\lib\site-packages\dbt\include\starter_project
[0m16:31:51.754458 [info ] [MainThread]: 
Your new dbt project "analytics_engineer" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m16:31:51.756634 [info ] [MainThread]: Setting up your profile.
[0m16:34:14.333453 [info ] [MainThread]: Profile analytics_engineer written to profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m16:34:14.337715 [debug] [MainThread]: Command `dbt init` succeeded at 16:34:14.336613 after 159.35 seconds
[0m16:34:14.339831 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8E46FF7C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8E6FFF5E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8E6FF5F40>]}
[0m16:34:14.340895 [debug] [MainThread]: Flushing usage events
[0m22:38:04.576423 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001321258F3A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013211DFB760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013214DD1A90>]}


============================== 22:38:04.587422 | 2771a74f-3a55-434d-9467-b0f75b7eedd3 ==============================
[0m22:38:04.587422 [info ] [MainThread]: Running with dbt=1.7.13
[0m22:38:04.588422 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\caioc\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt clean', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:38:04.590424 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\caioc\Desktop\AE\Analytics_Engineering_ADA\Analytics_Engineering_ADA\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:38:04.593453 [debug] [MainThread]: Command `dbt clean` failed at 22:38:04.592453 after 0.12 seconds
[0m22:38:04.595454 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001321258F3A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013214DD6B20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013214DD63D0>]}
[0m22:38:04.596425 [debug] [MainThread]: Flushing usage events
